///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String assetsLogoLoading = 'assets/images/logo_loading.gif';
  static const String assetsLogoSignet = 'assets/images/logo_signet.png';
  static const String fontsIconsFont = 'assets/fonts/IconsFont.ttf';
  static const String fontsIconsFontConfig = 'assets/fonts/icons_font_config.json';
  static const String arrows = 'assets/icons/arrows.svg';
  static const String ethereumLogo = 'assets/icons/ethereum_logo.svg';
  static const String kiraLogo = 'assets/icons/kira_logo.svg';
  static const String iconsNetworkStatus = 'assets/icons/network_status.svg';
}
